name: CI

on:
  push:
  pull_request:

jobs:
  ci:
    name: PHP ${{ matrix.php }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-22.04
        php:
          - 8.2
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: extension=ardillo
      - name: Prepare environment
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          pip3 install meson ninja
          sudo apt-get update -y
          sudo apt-get install -y libgtk-3-dev xvfb
          git clone https://github.com/ardillo-php/ext.git
          cd ext && git submodule update --init && phpize && ./configure && make -j && sudo make install && cd ..
      - name: Confirm Ardillo extension is installed/enabled
        run: xvfb-run -a php --ri ardillo
      - name: Install Composer dependencies
        run: xvfb-run -a composer install
      - name: Run PHPStan
        run: xvfb-run -a composer phpstan
      - name: Run Psalm
        run: xvfb-run -a composer psalm -- --output-format=github --shepherd
      - name: Run Test Suite
        uses: paambaati/codeclimate-action@v4.0.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        with:
          coverageCommand: xvfb-run -a php -d memory_limit=-1 ./vendor/bin/phpunit -c ./etc/phpunit.xml.dist --coverage-clover clover.xml
          coverageLocations: clover.xml:clover
          debug: true
